version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-strapi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecomm-sock
      MYSQL_USER: sock
      MYSQL_PASSWORD: sock123421@13
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: strapi-backend
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: ecomm-sock
      DATABASE_USERNAME: sock
      DATABASE_PASSWORD: sock123421@13
      DATABASE_SSL: "false"
    ports:
      - "1337:1337"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data:
